"""
Runner: connect real-data forecasters to the wagering mechanism.

Takes a 1D time series, runs 7 forecasters in a rolling fashion,
feeds their forecasts into the mechanism, and compares weighting rules.

Output format matches master_comparison for dashboard compatibility.
"""
from __future__ import annotations

import json
import os
import time

import numpy as np

from .forecasters import BaseForecaster, get_all_forecasters
from .stats import BOOTSTRAP_CI_SEED, diebold_mariano_test


# Pipeline-version tag embedded in forecast caches (see properties 1.3 / 2.3
# — caches without this tag are treated as stale). Caches without this
# exact string are treated as stale and regenerated by ensure_cache().
PIPELINE_VERSION = "v2-causal-norm"


def normalize_series(series: np.ndarray) -> tuple[np.ndarray, float, float]:
    """LEGACY — Whole-series min/max normalization.

    ⚠️  This routine uses min and max taken from the ENTIRE input array,
    which leaks future values into every training round and corrupts
    headline CRPS figures (data leakage fix: property 1.1). It is retained only for
    dashboard-display paths that explicitly need a full-range rescaling.
    All training-time callers SHALL use :func:`causal_normalize` instead.

    Raises
    ------
    ValueError
        If the input contains any NaN or infinite values. Callers must
        drop or impute non-finite values before normalising; silently
        propagating NaN through the pipeline has caused subtle bugs.
    """
    series = np.asarray(series, dtype=np.float64)
    if not np.all(np.isfinite(series)):
        n_bad = int(np.sum(~np.isfinite(series)))
        raise ValueError(
            f"normalize_series received {n_bad} non-finite value(s); "
            f"drop or impute NaN/inf before calling."
        )
    lo, hi = float(np.min(series)), float(np.max(series))
    if hi - lo < 1e-12:
        return np.full_like(series, 0.5), lo, hi
    return (series - lo) / (hi - lo), lo, hi


def causal_normalize(
    series: np.ndarray, warmup_len: int
) -> tuple[np.ndarray, float, float]:
    """Strictly-causal [0, 1] normalization using only ``series[:warmup_len]``.

    Computes ``lo = min(series[:warmup_len])`` and
    ``hi = max(series[:warmup_len])`` so that ``norm[:warmup_len]`` depends
    only on ``series[:warmup_len]``; for every ``t >= warmup_len``,
    altering ``series[t+1:]`` does not change ``norm[:t+1]``.

    This is the headline fix for the causal normalisation property (1.1 / 2.1 / 2.2)
    that prevents future-data leakage.

    Parameters
    ----------
    series : np.ndarray
        1D array of raw observations.
    warmup_len : int
        Number of initial observations used to fit the normalization
        constants. Must satisfy ``2 <= warmup_len <= len(series)``.

    Returns
    -------
    (norm, lo, hi) : tuple[np.ndarray, float, float]
        ``norm`` is the normalized series with the same shape as
        ``series``. ``lo``, ``hi`` are the (warmup-window) extremes used
        to scale it.

    Raises
    ------
    ValueError
        If the input contains any NaN or infinite values; if
        ``warmup_len < 2``; or if ``warmup_len > len(series)``.
    """
    series = np.asarray(series, dtype=np.float64)
    if not np.all(np.isfinite(series)):
        n_bad = int(np.sum(~np.isfinite(series)))
        raise ValueError(
            f"causal_normalize received {n_bad} non-finite value(s); "
            f"drop or impute NaN/inf before calling."
        )
    if warmup_len < 2:
        raise ValueError(
            f"causal_normalize: warmup_len={warmup_len} must be >= 2."
        )
    if warmup_len > len(series):
        raise ValueError(
            f"causal_normalize: warmup_len={warmup_len} exceeds series "
            f"length {len(series)}."
        )
    lo = float(np.min(series[:warmup_len]))
    hi = float(np.max(series[:warmup_len]))
    if hi - lo < 1e-12:
        return np.full_like(series, 0.5), lo, hi
    # Clip to [0, 1]: values in series[warmup_len:] can fall outside the
    # warmup-window range. The downstream mechanism (and quantile scoring)
    # requires y ∈ [0, 1]; the alternative of letting values escape the
    # unit interval breaks the Lambert bounded-score guarantee. This
    # choice is documented in bugfix design §Fix Implementation.
    return np.clip((series - lo) / (hi - lo), 0.0, 1.0), lo, hi


def causal_normalize_expanding(
    series: np.ndarray, warmup_len: int
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Strictly-causal [0, 1] normalization with an EXPANDING window.

    Refits ``(lo, hi)`` as ``series[:t]`` grows: ``lo_t = min(series[:t+1])``,
    ``hi_t = max(series[:t+1])`` for every ``t >= warmup_len``, while
    rounds ``t < warmup_len`` use the static warmup-window scale. This
    addresses post-audit issue #8: with the static warmup-window scale
    (``causal_normalize``), observations in the evaluation window that
    exceed the warmup range get clipped to 1.0, compressing tail CRPS.

    The expanding-window variant preserves strict causality (``norm[t]``
    still depends only on ``series[:t+1]``) while never clipping.

    Returns
    -------
    (norm, lo_trajectory, hi_trajectory) : tuple[np.ndarray, np.ndarray, np.ndarray]
        ``norm`` has the same shape as ``series``.
        ``lo_trajectory[t]``, ``hi_trajectory[t]`` are the ``(lo, hi)``
        used at round ``t``.

    Raises
    ------
    ValueError
        Same validations as :func:`causal_normalize`.
    """
    series = np.asarray(series, dtype=np.float64)
    if not np.all(np.isfinite(series)):
        n_bad = int(np.sum(~np.isfinite(series)))
        raise ValueError(
            f"causal_normalize_expanding received {n_bad} non-finite value(s); "
            f"drop or impute NaN/inf before calling."
        )
    if warmup_len < 2:
        raise ValueError(
            f"causal_normalize_expanding: warmup_len={warmup_len} must be >= 2."
        )
    if warmup_len > len(series):
        raise ValueError(
            f"causal_normalize_expanding: warmup_len={warmup_len} exceeds "
            f"series length {len(series)}."
        )
    T = len(series)
    # Running cumulative min/max.
    cum_min = np.minimum.accumulate(series)
    cum_max = np.maximum.accumulate(series)

    lo_traj = np.empty(T, dtype=np.float64)
    hi_traj = np.empty(T, dtype=np.float64)
    # Warmup window: static scale derived from series[:warmup_len]
    lo_warm = float(np.min(series[:warmup_len]))
    hi_warm = float(np.max(series[:warmup_len]))
    lo_traj[:warmup_len] = lo_warm
    hi_traj[:warmup_len] = hi_warm
    # Evaluation window: expanding scale from cumulative statistics.
    lo_traj[warmup_len:] = cum_min[warmup_len:]
    hi_traj[warmup_len:] = cum_max[warmup_len:]

    denom = hi_traj - lo_traj
    # Guard degenerate rounds (constant history) with a flat 0.5.
    norm = np.where(
        denom > 1e-12,
        (series - lo_traj) / np.where(denom > 1e-12, denom, 1.0),
        0.5,
    )
    # Clip is defensive here — with cum min/max, values are within
    # [lo_t, hi_t] by construction, so clipping is a no-op on evaluation
    # rounds. It still guards round-t where t is in [0, warmup_len).
    norm = np.clip(norm, 0.0, 1.0)
    return norm, lo_traj, hi_traj


def best_single_by_crps(
    agent_rolling_crps: list[list[float]], lookback: int = 100
) -> int:
    """Return index of the forecaster with lowest mean CRPS over the
    last ``lookback`` per-agent observations.

    Shared helper used identically by :func:`run_real_data_comparison`
    and :func:`onlinev2.real_data.experiments._run_horizon_comparison`
    so the ``best_single`` baseline row is computed under a single
    definition across runners (best_single consistency property 1.11 / 2.11).

    Parameters
    ----------
    agent_rolling_crps : list[list[float]]
        Per-agent CRPS history, one list per forecaster. Lists may be
        of different lengths; only the last ``lookback`` entries of
        each are used.
    lookback : int
        Number of most-recent CRPS values to include in the mean.

    Returns
    -------
    int
        Index of the agent with the minimum mean-CRPS tail. Agents with
        empty histories rank as ``+inf`` (i.e. will not be selected).
    """
    recent = [
        float(np.mean(h[-lookback:])) if len(h) >= 1 else float("inf")
        for h in agent_rolling_crps
    ]
    return int(np.argmin(recent))


def run_real_data_comparison(
    series: np.ndarray,
    forecasters: list[BaseForecaster] | None = None,
    warmup: int = 100,
    taus: np.ndarray | None = None,
    outdir: str = "outputs",
    series_name: str = "real_data",
    gamma: float = 4.0,
    rho: float = 0.1,
    lam: float = 0.05,
    recalibrate: bool = False,
    seed: int = 42,
    strict_no_fallback: bool = False,
    sweep_artefact: str | None = None,
    normalize_mode: str = "static",
) -> dict:
    """Run all forecasters on a real time series and compare weighting rules.

    Args:
        series: 1D array of observed values (raw, will be normalized)
        forecasters: list of forecaster objects (default: all 7)
        warmup: number of initial rounds used only for training (no scoring)
        taus: quantile levels for CRPS-hat. Default is the 9-level
            equidistant grid ``[0.1, 0.2, ..., 0.9]``, which is the
            post-audit canonical grid (see `onlinev2/src/onlinev2/
            core/scoring.py::TAUS_FINE`). The 5-level non-equidistant
            legacy grid ``[0.1, 0.25, 0.5, 0.75, 0.9]`` silently drops
            about 20% of the classical CRPS integration range when the
            simple ``(2/K) * sum pinball`` formula is used; prefer the
            default unless you have a specific reason to override.
        outdir: output directory
        series_name: name for the output files
        gamma: EWMA loss-to-skill sensitivity (default 4.0, tuned: 16.0)
        rho: EWMA learning rate (default 0.1, tuned: 0.5)
        lam: skill gate floor (default 0.05)
        recalibrate: when True, attach an additive post-hoc rolling isotonic
            recalibration layer on top of the mechanism's aggregate quantile
            output and emit an extra ``mechanism_recal`` baseline row. When
            False (the default) the runner output is bit-identical to the
            pre-feature baseline. See Kuleshov, Fenner and Ermon (2018,
            arXiv:1807.00263, §3.1). Applies the rolling recalibration layer
            (``onlinev2.core.recalibration``) when enabled.
        seed: Deterministic seed forwarded to forecasters (MLP) so results
            are reproducible across changes to the retraining schedule.
            Bugfix clause 1.8 / 2.8.
        strict_no_fallback: If True, raise ``ValueError`` at end-of-run
            when any forecaster's ``fallback_counter > 0`` (i.e. an ML
            model silently reduced to persistence). Bugfix clauses
            1.9, 1.16 / 2.9, 2.16.
        sweep_artefact: Optional path to a ``sensitivity_sweep.json``
            produced by ``scripts/run_sensitivity_sweep.py``. When
            provided, ``optimal_improvement_pct`` in the emitted
            ``sensitivity`` block is read from that file rather than
            hardcoded. Bugfix clause 1.4 / 2.4.
        normalize_mode: ``"static"`` (default) uses
            :func:`causal_normalize` with ``(lo, hi)`` frozen to the
            warmup-window range. This preserves bit-identity with the
            main regenerated dashboard JSONs but clips evaluation-window
            observations outside the warmup range (up to ~33% of the
            Elia wind eval window gets clipped to 0 or 1). ``"expanding"``
            uses :func:`causal_normalize_expanding` which refits
            ``(lo_t, hi_t) = (min, max) of series[:t+1]`` for every
            ``t >= warmup`` while keeping strict causality. Expanding
            avoids clipping but the ``(lo, hi)`` used at round t depends
            on the evaluation path seen up to t, so it is not strictly
            equivalent across re-runs of different series prefixes.
            Post-audit issue #1 (see
            ``onlinev2/outputs/post_fix_deltas/SUMMARY.md``).

    Returns:
        dict with 'config', 'rows' (master_comparison format), 'per_round'
    """
    if taus is None:
        taus = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
    if forecasters is None:
        forecasters = get_all_forecasters()
    if normalize_mode not in {"static", "expanding"}:
        raise ValueError(
            f"normalize_mode must be 'static' or 'expanding', got {normalize_mode!r}."
        )

    n_forecasters = len(forecasters)
    T = len(series)

    # Strictly-causal normalization. ``static`` (default) freezes (lo, hi)
    # to the warmup window; ``expanding`` refits them over series[:t+1].
    # Both variants preserve the Property-1 causal-dependence invariant
    # (causal normalisation property 1.1 / 2.1).
    # See post-audit issue #1 for the clipping tradeoff.
    if normalize_mode == "expanding":
        norm_series, lo_traj, hi_traj = causal_normalize_expanding(
            series, warmup_len=warmup
        )
        s_min = float(lo_traj[-1])
        s_max = float(hi_traj[-1])
    else:
        norm_series, s_min, s_max = causal_normalize(series, warmup_len=warmup)

    # Propagate deterministic seed to forecasters that support it
    # (MLP seed determinism property 1.8 / 2.8). Currently MLPForecaster.seed.
    for fc in forecasters:
        if hasattr(fc, "seed"):
            fc.seed = seed

    print(f"Running {n_forecasters} forecasters on {T} data points "
          f"(warmup={warmup}, series={series_name}, normalize_mode={normalize_mode})")

    # Storage
    y_all = np.zeros(T)
    reports = np.zeros((n_forecasters, T))  # point forecasts
    q_reports = np.zeros((n_forecasters, T, len(taus)))  # quantile forecasts

    t0 = time.time()

    for t in range(T):
        y_t = norm_series[t]
        y_all[t] = y_t
        history = norm_series[:t]  # strictly causal

        # Causality invariant: predict() and predict_quantiles() use data up to t-1.
        # update_residuals() incorporates the round-t outcome AFTER predictions are made.
        for i, fc in enumerate(forecasters):
            # Retrain policy:
            # - Always fit at t=0 if history is non-empty (but since history=[]
            #   at t=0, this branch is never taken in the main runner loop).
            # - Otherwise fit every `retrain_every` rounds, and only once
            #   enough history exists (min 20 points).
            # This prevents a spurious fallback-counter bump at t=0 where an
            # empty history is passed to fit() for no informational gain.
            # Forecasters individually decide whether they have enough data
            # (XGBoost / MLP / ARIMA each impose their own thresholds).
            if t % fc.retrain_every == 0 and len(history) > 20:
                fc.fit(history)

            # Predict
            point = fc.predict()
            # NaN guard: np.clip preserves NaN, so a degenerate forecaster
            # (e.g. ARIMA fit producing NaN) could poison `reports[i, t]`
            # and cascade through the mechanism. Substitute the last-known
            # history value (or 0.5 if history is empty) and count the
            # fallback so the runner-level audit surfaces it.
            if not np.isfinite(point):
                fc.fallback_counter += 1
                point = float(history[-1]) if len(history) > 0 else 0.5
            point = float(np.clip(point, 0, 1))
            reports[i, t] = point
            q_reports[i, t, :] = fc.predict_quantiles(taus)

            # Update residuals for quantile estimation
            fc.update_residuals(y_t, point)

            # Update history for models that track it
            if hasattr(fc, '_history'):
                fc._history = norm_series[:t + 1]
            if hasattr(fc, '_last') and isinstance(fc._last, float):
                fc._last = y_t

    elapsed = time.time() - t0
    print(f"  Forecasting done in {elapsed:.1f}s")

    # Now run the mechanism comparison
    from onlinev2.core.aggregation import aggregate_forecast
    from onlinev2.core.scoring import crps_hat_from_quantiles
    from onlinev2.simulation import run_simulation

    # Run simulation with the mechanism
    print(f"  Running mechanism simulation (γ={gamma}, ρ={rho}, λ={lam})...")
    res = run_simulation(
        T=T,
        n_forecasters=n_forecasters,
        missing_prob=0.0,
        seed=42,
        scoring_mode="quantiles_crps",
        taus=taus,
        y_pre=y_all,
        q_reports_pre=q_reports,
        forecaster_noise_pre=np.ones(n_forecasters),
        store_history=True,
        deposit_mode="fixed",
        fixed_deposit=1.0,
        eta=2.0,
        lam=lam,
        gamma=gamma,
        rho=rho,
        omega_max=0.0,
    )

    # Compute CRPS for each weighting rule (post-warmup)
    eps = 1e-12
    rules = ["uniform", "skill", "mechanism", "best_single",
             "inverse_variance", "trimmed_mean", "median"]
    crps_per_rule: dict[str, list[float]] = {r: [] for r in rules}
    per_round: list[dict] = []

    # Track per-agent rolling CRPS for inverse-variance weights
    agent_rolling_crps: list[list[float]] = [[] for _ in range(n_forecasters)]

    # --- Optional post-hoc rolling isotonic recalibration of the mechanism
    #     aggregate (additive; inert when recalibrate=False). -------------
    # Post-hoc rolling isotonic recalibration of the mechanism aggregate.
    # See Kuleshov, Fenner and Ermon (2018), arXiv:1807.00263, §3.1.
    # Applies the rolling recalibration layer (``onlinev2.core.recalibration``) when enabled.
    rc = None
    r_recal_cache: list[np.ndarray] = []
    if recalibrate:
        from onlinev2.core.recalibration import RollingRecalibrator
        rc = RollingRecalibrator(
            taus, window_size=500, min_pits=100, refit_every=50
        )
        crps_per_rule["mechanism_recal"] = []

    for t in range(warmup, T):
        y_t = float(y_all[t])
        q_t = q_reports[:, t, :]

        # Per-agent CRPS this round (vectorised — pass full matrix at once)
        agent_crps_t = crps_hat_from_quantiles(y_t, q_t, taus)

        # Uniform
        agg_u = np.mean(q_t, axis=0)
        c_u = float(crps_hat_from_quantiles(y_t, agg_u.reshape(1, -1), taus)[0])
        crps_per_rule["uniform"].append(c_u)

        # Skill-only
        sigma_t = res["sigma_hist"][:, t]
        w_skill = sigma_t.copy()
        if w_skill.sum() > eps:
            agg_s = aggregate_forecast(q_t, w_skill, eps=eps)
            c_s = float(crps_hat_from_quantiles(y_t, agg_s.reshape(1, -1), taus)[0])
        else:
            c_s = c_u
        crps_per_rule["skill"].append(c_s)

        # Mechanism (from simulation)
        r_mech = np.asarray(res["r_hat_hist"][t], dtype=np.float64)
        if r_mech.size == len(taus):
            c_m = float(crps_hat_from_quantiles(y_t, r_mech.reshape(1, -1), taus)[0])
        else:
            c_m = c_u
        crps_per_rule["mechanism"].append(c_m)

        # Best single (lowest recent CRPS — uses quantile quality, not just point accuracy)
        # Shared helper with _run_horizon_comparison (best_single consistency property 1.11 / 2.11).
        if t - warmup >= 20:
            best_idx = best_single_by_crps(agent_rolling_crps, lookback=100)
        else:
            best_idx = 0
        c_best = float(crps_hat_from_quantiles(y_t, q_t[best_idx:best_idx+1], taus)[0])
        crps_per_rule["best_single"].append(c_best)

        # --- NEW: Inverse-variance weighting (Bates-Granger style) ---
        # Weights proportional to 1/mean(recent CRPS) — better agents get more weight
        if t - warmup >= 20:
            inv_var_w = np.zeros(n_forecasters)
            for i in range(n_forecasters):
                recent = agent_rolling_crps[i][-100:]
                mean_crps_i = np.mean(recent) + eps
                inv_var_w[i] = 1.0 / mean_crps_i
            inv_var_w /= inv_var_w.sum()
            agg_iv = np.sum(inv_var_w[:, None] * q_t, axis=0)
        else:
            agg_iv = agg_u
        c_iv = float(crps_hat_from_quantiles(y_t, agg_iv.reshape(1, -1), taus)[0])
        crps_per_rule["inverse_variance"].append(c_iv)

        # --- NEW: Trimmed mean (drop worst, average rest) ---
        # Drop the forecaster with highest recent CRPS. With n == 1
        # there is nothing to trim to, and the empty-slice mean would
        # be NaN — fall back to the uniform aggregate in that case.
        if t - warmup >= 20 and n_forecasters >= 2:
            recent_means = [np.mean(agent_rolling_crps[i][-100:]) for i in range(n_forecasters)]
            worst_idx = int(np.argmax(recent_means))
            keep_mask = np.ones(n_forecasters, dtype=bool)
            keep_mask[worst_idx] = False
            agg_trim = np.mean(q_t[keep_mask], axis=0)
        else:
            agg_trim = agg_u
        c_trim = float(crps_hat_from_quantiles(y_t, agg_trim.reshape(1, -1), taus)[0])
        crps_per_rule["trimmed_mean"].append(c_trim)

        # --- NEW: Median forecast (per-quantile median across forecasters) ---
        agg_med = np.median(q_t, axis=0)
        c_med = float(crps_hat_from_quantiles(y_t, agg_med.reshape(1, -1), taus)[0])
        crps_per_rule["median"].append(c_med)

        # Update rolling CRPS AFTER all selection/scoring so the lookback
        # window contains only rounds < t (F2 fix: eliminates 1% look-ahead).
        for i in range(n_forecasters):
            agent_rolling_crps[i].append(agent_crps_t[i])
            if len(agent_rolling_crps[i]) > 500:
                agent_rolling_crps[i] = agent_rolling_crps[i][-500:]

        per_round.append({
            "t": t,
            "y": y_t,
            "crps_uniform": c_u,
            "crps_skill": c_s,
            "crps_mechanism": c_m,
            "crps_best_single": c_best,
            "crps_inverse_variance": c_iv,
            "crps_trimmed_mean": c_trim,
            "crps_median": c_med,
        })

        # --- Optional recalibration hook (strictly additive) -----------
        # Update the rolling recalibrator with (r_mech, y_t), refit on
        # the configured cadence, and append mechanism_recal CRPS. The
        # per-round dict gets an extra key *only when* recalibrate=True,
        # preserving bit-identity of the default path.
        # Bugfix clause 1.10 / 2.10: reorder to
        #   transform → score → update → (refit on cadence)
        # so the recalibration map G applied at round t was fitted
        # only on PITs from rounds < t. The legacy order
        # (update → refit → transform) let the current round's y enter
        # the PIT buffer before the transform, leaking into the next
        # refit window.
        if recalibrate and rc is not None:
            r_mech_t = np.asarray(res["r_hat_hist"][t], dtype=np.float64)
            if r_mech_t.size == len(taus):
                # 1. transform with G_{t-1} (fitted only on PITs from
                #    rounds < t)
                r_recal_t = rc.transform(r_mech_t)
                # 2. score is appended below (c_recal)
                # 3. then update the PIT buffer with (r_mech_t, y_t)
                rc.update(r_mech_t, y_t)
                # 4. refit on cadence
                idx_rel = t - warmup
                if idx_rel % rc.refit_every == 0 and rc.n_pits >= rc.min_pits:
                    try:
                        rc.fit()
                    except Exception as e:
                        print(f"  recalibration fit failed: {e}")
            else:
                # mechanism aggregate unavailable — fall back to the
                # input q_t mean so downstream CRPS is still well-defined.
                r_recal_t = np.mean(q_t, axis=0)
            r_recal_cache.append(np.asarray(r_recal_t, dtype=np.float64))
            c_recal = float(
                crps_hat_from_quantiles(y_t, r_recal_t.reshape(1, -1), taus)[0]
            )
            crps_per_rule["mechanism_recal"].append(c_recal)
            per_round[-1]["crps_mechanism_recal"] = c_recal

    # --- Oracle comparison (uses agent_crps_t already computed in main loop) ---
    # Re-compute oracle in a fast vectorised pass
    # --- Oracle-like baselines ---
    # Two flavours are emitted here, each with a precise interpretation:
    #
    # 1. `oracle` (per-round argmin): at each round t, use the single
    #    forecaster with the lowest per-agent CRPS at round t. This is
    #    the tight per-round oracle — a lower bound that no per-round
    #    adaptive weighting can beat. Uses round-t y_t (hindsight).
    #
    # 2. `per_round_inv_crps_hindsight`: at each round t, weight
    #    forecasters by 1 / agent_crps_t and combine. This is the
    #    legacy `oracle` row (post-audit #2 correction). Inverse-CRPS
    #    weights are neither a per-round oracle nor a fixed-weight
    #    hindsight oracle; the row is kept under an honest label for
    #    back-compat comparisons.
    print("  Computing oracle baselines...")
    crps_oracle = []
    crps_inv_crps_hindsight = []
    for idx in range(len(per_round)):
        t = warmup + idx
        y_t = float(y_all[t])
        q_t = q_reports[:, t, :]
        agent_crps = crps_hat_from_quantiles(y_t, q_t, taus)

        # Per-round argmin: pick the best single forecaster at round t.
        best_agent_idx = int(np.argmin(agent_crps))
        c_oracle = float(agent_crps[best_agent_idx])
        crps_oracle.append(c_oracle)
        per_round[idx]["crps_oracle"] = c_oracle

        # Legacy inverse-CRPS-hindsight weighting (renamed).
        inv_crps = np.divide(
            1.0, agent_crps,
            out=np.zeros_like(agent_crps),
            where=agent_crps > 1e-12,
        )
        if inv_crps.sum() > 1e-12:
            w = inv_crps / inv_crps.sum()
            agg_inv = np.sum(w[:, None] * q_t, axis=0)
        else:
            agg_inv = np.mean(q_t, axis=0)
        c_inv = float(
            crps_hat_from_quantiles(y_t, agg_inv.reshape(1, -1), taus)[0]
        )
        crps_inv_crps_hindsight.append(c_inv)
        per_round[idx]["crps_per_round_inv_crps_hindsight"] = c_inv

    crps_per_rule["oracle"] = crps_oracle
    crps_per_rule["per_round_inv_crps_hindsight"] = crps_inv_crps_hindsight

    # --- michael_ogd_centered_median_fan baseline ---
    # Bugfix clause 1.12 / 2.12: renamed from the legacy `michael_ogd`
    # label to reflect what the code actually computes. Michael's OGD
    # algorithm is run only to produce a single-τ point series; the
    # quantile fan scored here is the ENSEMBLE's per-τ median shifted
    # by (y_hat - ensemble_median_at_central_τ). A true per-τ OGD
    # implementation is flagged as follow-up
    # (optional diagnostic: sensitivity sweep artefact).
    print("  Computing michael_ogd_centered_median_fan baseline...")
    try:
        from onlinev2.mechanism.michael_port import run_main_rewards as _michael_run
        crps_mich_fan: list[float] = []
        tau_mid_idx = len(taus) // 2  # τ ≈ 0.5
        # F7 fix: give Michael OGD the full series (including warmup) so its
        # EWMA weights converge before scoring — parity with the mechanism.
        panel_pt_full = q_reports[:, :T, tau_mid_idx].T  # shape (T, N)
        try:
            mich = _michael_run(panel_pt_full, y_all[:T], {"quantile": 0.5, "eta": 0.01})
            y_hat_full = mich["y_hat"]  # shape (T,)
            for idx in range(len(per_round)):
                y_t = float(y_all[warmup + idx])
                y_hat_t = float(y_hat_full[warmup + idx])
                q_t = q_reports[:, warmup + idx, :]
                ens_median_per_tau = np.median(q_t, axis=0)
                offset = y_hat_t - ens_median_per_tau[tau_mid_idx]
                agg_michael = ens_median_per_tau + offset
                c_mich = float(
                    crps_hat_from_quantiles(
                        y_t, agg_michael.reshape(1, -1), taus
                    )[0]
                )
                crps_mich_fan.append(c_mich)
                per_round[idx]["crps_michael_ogd_centered_median_fan"] = c_mich
            crps_per_rule["michael_ogd_centered_median_fan"] = crps_mich_fan
        except Exception as e:
            print(f"  michael_ogd_centered_median_fan baseline failed: {e}")
            crps_per_rule["michael_ogd_centered_median_fan"] = [
                float("nan")
            ] * len(per_round)
    except ImportError:
        pass

    # Summary
    mean_uniform = float(np.mean(crps_per_rule["uniform"]))
    mean_mechanism = float(np.mean(crps_per_rule["mechanism"]))

    # Block-bootstrap 95% CIs on the paired ``delta_crps_vs_equal = mean(d)
    # where d_t = method(t) - uniform(t)``. The stationary (circular) block
    # bootstrap preserves the autocorrelation structure of real-data losses
    # that a naive iid bootstrap would destroy. See ``stats.bootstrap_ci``.
    # Bandwidth picked to ≈ one week of hourly wind (168 h) or the closest
    # equivalent for a given T.
    from .stats import bootstrap_ci as _bootstrap_ci
    crps_uniform_arr_for_ci = np.asarray(crps_per_rule["uniform"], dtype=np.float64)
    _ci_block_size = max(20, min(168, len(crps_uniform_arr_for_ci) // 20))
    _ci_cache: dict[str, dict] = {}

    def _delta_ci_for_rule(rule_name: str) -> dict:
        """Return the 95% block-bootstrap CI on mean(method - uniform)."""
        if rule_name in _ci_cache:
            return _ci_cache[rule_name]
        if rule_name == "uniform":
            ci = {
                "delta_ci_lower": 0.0,
                "delta_ci_upper": 0.0,
                "delta_bootstrap_se": 0.0,
            }
        else:
            method_arr = np.asarray(crps_per_rule[rule_name], dtype=np.float64)
            # Align lengths and drop NaN rows jointly.
            n_align = min(len(method_arr), len(crps_uniform_arr_for_ci))
            m = method_arr[:n_align]
            u = crps_uniform_arr_for_ci[:n_align]
            mask = np.isfinite(m) & np.isfinite(u)
            if mask.sum() < 50:
                ci = {
                    "delta_ci_lower": float("nan"),
                    "delta_ci_upper": float("nan"),
                    "delta_bootstrap_se": float("nan"),
                }
            else:
                # bootstrap_ci returns mean_diff = mean(losses_1 - losses_2);
                # we pass (method, uniform) so mean_diff == delta_crps_vs_equal.
                ci_raw = _bootstrap_ci(
                    m[mask],
                    u[mask],
                    n_bootstrap=1000,
                    block_size=_ci_block_size,
                    alpha=0.05,
                    seed=BOOTSTRAP_CI_SEED,
                )
                ci = {
                    "delta_ci_lower": round(ci_raw["ci_lower"], 6),
                    "delta_ci_upper": round(ci_raw["ci_upper"], 6),
                    "delta_bootstrap_se": round(ci_raw["bootstrap_se"], 6),
                }
        _ci_cache[rule_name] = ci
        return ci

    rows = []
    for rule in rules + [
        "oracle",
        "per_round_inv_crps_hindsight",
        "michael_ogd_centered_median_fan",
    ]:
        if rule not in crps_per_rule:
            continue
        values = crps_per_rule[rule]
        # filter NaN defensively for the summary aggregate
        valid = [v for v in values if not (isinstance(v, float) and np.isnan(v))]
        mean_crps = float(np.mean(valid)) if valid else float("nan")
        row = {
            "experiment": f"real_data_{series_name}",
            "method": rule,
            "seed": 0,
            "DGP": series_name,
            "preset": "fixed_deposits",
            "mean_crps": mean_crps,
            "delta_crps_vs_equal": mean_crps - mean_uniform,
        }
        row.update(_delta_ci_for_rule(rule))
        rows.append(row)

    # --- Recalibration summary row (additive; recalibrate=True only) ---
    if recalibrate and "mechanism_recal" in crps_per_rule:
        values = crps_per_rule["mechanism_recal"]
        valid = [v for v in values if not (isinstance(v, float) and np.isnan(v))]
        mean_crps_recal = float(np.mean(valid)) if valid else float("nan")
        row = {
            "experiment": f"real_data_{series_name}",
            "method": "mechanism_recal",
            "seed": 0,
            "DGP": series_name,
            "preset": "fixed_deposits",
            "mean_crps": mean_crps_recal,
            "delta_crps_vs_equal": mean_crps_recal - mean_uniform,
        }
        row.update(_delta_ci_for_rule("mechanism_recal"))
        rows.append(row)

    result = {
        "config": {
            "T": T,
            "n_forecasters": n_forecasters,
            "warmup": warmup,
            "series_name": series_name,
            "series_min": s_min,
            "series_max": s_max,
            "forecasters": [fc.name for fc in forecasters],
            "gamma": gamma,
            "rho": rho,
            "lam": lam,
            "normalize_mode": normalize_mode,
        },
        "rows": rows,
        "per_round": per_round,
    }

    # --- Rolling window analysis (1000-round windows) ---
    window_size = min(1000, (T - warmup) // 4)
    rolling_improvement = []
    crps_u_arr = np.array(crps_per_rule["uniform"])
    crps_m_arr = np.array(crps_per_rule["mechanism"])
    crps_best_arr = np.array(crps_per_rule["best_single"])
    step_roll = max(1, len(crps_u_arr) // 200)
    for start in range(0, len(crps_u_arr) - window_size, step_roll):
        end = start + window_size
        u_window = np.mean(crps_u_arr[start:end])
        m_window = np.mean(crps_m_arr[start:end])
        b_window = np.mean(crps_best_arr[start:end])
        pct_vs_uniform = (m_window - u_window) / u_window * 100 if u_window > 0 else 0
        pct_vs_best = (m_window - b_window) / b_window * 100 if b_window > 0 else 0
        rolling_improvement.append({
            "t_start": warmup + start,
            "t_end": warmup + end,
            "pct_improvement": round(pct_vs_uniform, 2),
            "pct_vs_best_single": round(pct_vs_best, 2),
        })
    result["rolling_improvement"] = rolling_improvement

    # --- Temporal stability: first-half / second-half comparison ---
    # (Renamed from "train_test_split" — the mechanism runs online so there
    #  is no true train/test separation; this checks temporal stability.)
    half = len(crps_u_arr) // 2
    first_vs_second = {}
    # Need at least 2 scored rounds for a meaningful half/half split.
    # With fewer, `arr[:half]` is empty and np.mean emits a
    # "Mean of empty slice" RuntimeWarning and returns NaN.
    if half >= 1 and len(crps_u_arr) >= 2:
        for method_name in crps_per_rule:
            arr = np.array(crps_per_rule[method_name])
            first_mean = float(np.mean(arr[:half]))
            second_mean = float(np.mean(arr[half:]))
            first_vs_second[method_name] = {
                "first_half_crps": round(first_mean, 6),
                "second_half_crps": round(second_mean, 6),
                "first_half_delta_vs_uniform": round(first_mean - float(np.mean(crps_u_arr[:half])), 6),
                "second_half_delta_vs_uniform": round(second_mean - float(np.mean(crps_u_arr[half:])), 6),
            }
    result["temporal_stability"] = {
        "description": (
            "First-half vs second-half mean CRPS across the SAME online "
            "run. Not a train/test split — the mechanism sees both "
            "halves in sequence. Use to detect drift, not to estimate "
            "generalization."
        ),
        "first_half_rounds": half,
        "second_half_rounds": len(crps_u_arr) - half,
        "methods": first_vs_second,
    }
    # Deprecated alias (post-audit #7): the key name claims a train/test
    # protocol that this block does not perform. Kept to avoid breaking
    # existing dashboard adapters, but the payload now explicitly warns
    # that the numbers come from a single online run sliced in half.
    result["train_test_split"] = {
        "description": (
            "DEPRECATED alias of `temporal_stability`. Name preserved for "
            "backward compatibility; child keys renamed to first_half_* / "
            "second_half_* so they no longer falsely imply a refitted "
            "train/test evaluation. See `temporal_stability` for the "
            "canonical block."
        ),
        "first_half_rounds": half,
        "second_half_rounds": len(crps_u_arr) - half,
        "methods": {
            m: {
                "first_half_crps": v["first_half_crps"],
                "second_half_crps": v["second_half_crps"],
                "first_half_delta_vs_uniform": v["first_half_delta_vs_uniform"],
                "second_half_delta_vs_uniform": v["second_half_delta_vs_uniform"],
            }
            for m, v in first_vs_second.items()
        },
    }

    # --- Online-run per-block mean CRPS (online-run CRPS diagnostic property 1.14 / 2.14) ---
    # This block averages per-round CRPS from a single online run over K
    # sequential blocks. The label was previously "prequential_blocks"
    # and cited Dawid 1984 / Cerqueira 2020, but no forecaster is refitted
    # per block; a real prequential evaluation requires per-block refit
    # and is flagged as a follow-up for a true prequential evaluation.
    K_preq = 5
    n_scored = len(crps_u_arr)
    block_size_preq = n_scored // K_preq
    online_block_mean_methods: dict[str, dict] = {}
    # Need at least K_preq >= 2 scored rounds per block for the
    # sequential-block breakdown to be well-defined. When n_scored is
    # too small to populate the grid, emit an empty methods dict with a
    # note instead of producing NaN means from empty slices.
    if block_size_preq >= 1 and n_scored >= K_preq:
        for method_name in crps_per_rule:
            arr = np.array(crps_per_rule[method_name])
            block_test_crps = []
            block_test_delta = []
            for k in range(1, K_preq):
                b_start = k * block_size_preq
                b_end = (k + 1) * block_size_preq if k < K_preq - 1 else n_scored
                test_mean = float(np.mean(arr[b_start:b_end]))
                u_test_mean = float(np.mean(crps_u_arr[b_start:b_end]))
                block_test_crps.append(round(test_mean, 6))
                block_test_delta.append(round(test_mean - u_test_mean, 6))
            online_block_mean_methods[method_name] = {
                "block_test_crps": block_test_crps,
                "block_test_delta_vs_uniform": block_test_delta,
                "mean_test_crps": round(float(np.mean(block_test_crps)), 6),
                "std_test_crps": round(float(np.std(block_test_crps, ddof=1)), 6),
                "mean_test_delta": round(float(np.mean(block_test_delta)), 6),
            }
    result["online_block_mean"] = {
        "description": "Windowed mean of a single online run, bucketed into K "
                       "sequential blocks. NOT a prequential evaluation — no "
                       "per-block refit of forecasters or mechanism state. "
                       "Rename of legacy 'prequential_blocks' key; see "
                       "the methodology audit.",
        "n_blocks": K_preq,
        "block_size": block_size_preq,
        "test_blocks": K_preq - 1,
        "methods": online_block_mean_methods,
    }

    # --- Online-run windowed mean (windowed CRPS diagnostic property 1.13 / 2.13) ---
    # This block averages per-round CRPS from a single online run over
    # randomly-placed evaluation windows. The label was previously
    # "rep_holdout" and cited Cerqueira 2020 / Tashman 2000 as a
    # repeated-holdout evaluation, but no forecaster is refitted per
    # split; a real repeated-holdout evaluation requires refitting on
    # each train/test split and is flagged as a follow-up for the stronger
    # repeated-holdout implementation.
    nreps = 10
    train_frac = 0.6
    test_frac = 0.1
    train_len = int(n_scored * train_frac)
    test_len = int(n_scored * test_frac)
    rng = np.random.RandomState(42)
    lo_split = train_len
    hi_split = n_scored - test_len
    if hi_split > lo_split:
        split_points = sorted(rng.randint(lo_split, hi_split, size=nreps).tolist())
    else:
        split_points = [n_scored // 2]
    online_window_mean_methods: dict[str, dict] = {}
    for method_name in crps_per_rule:
        arr = np.array(crps_per_rule[method_name])
        rep_test_crps = []
        rep_test_delta = []
        for sp in split_points:
            t_start = sp
            t_end = min(sp + test_len, n_scored)
            test_mean = float(np.mean(arr[t_start:t_end]))
            u_test_mean = float(np.mean(crps_u_arr[t_start:t_end]))
            rep_test_crps.append(round(test_mean, 6))
            rep_test_delta.append(round(test_mean - u_test_mean, 6))
        online_window_mean_methods[method_name] = {
            "rep_test_crps": rep_test_crps,
            "rep_test_delta_vs_uniform": rep_test_delta,
            "mean_test_crps": round(float(np.mean(rep_test_crps)), 6),
            "std_test_crps": round(float(np.std(rep_test_crps, ddof=1)), 6),
            "mean_test_delta": round(float(np.mean(rep_test_delta)), 6),
        }
    result["online_window_mean"] = {
        "description": "Windowed mean of a single online run, averaged over "
                       "multiple randomly-placed evaluation windows. NOT a "
                       "repeated-holdout evaluation — no per-split refit of "
                       "forecasters or mechanism state. Rename of legacy "
                       "'rep_holdout' key; see "
                       "the methodology audit.",
        "n_reps": len(split_points),
        "train_frac": train_frac,
        "test_frac": test_frac,
        "train_len": train_len,
        "test_len": test_len,
        "split_points": split_points,
        "methods": online_window_mean_methods,
    }

    # --- Aggregate calibration (PIT for mechanism's quantile forecast) ---
    # For each round, check if y falls below each quantile level
    pit_counts = {float(tau): 0 for tau in taus}
    n_scored = 0
    for t in range(warmup, T):
        y_t = float(y_all[t])
        r_mech = np.asarray(res["r_hat_hist"][t], dtype=np.float64)
        if r_mech.size == len(taus):
            n_scored += 1
            for k, tau in enumerate(taus):
                if y_t <= r_mech[k]:
                    pit_counts[float(tau)] += 1
    calibration = []
    if n_scored > 0:
        for tau in taus:
            empirical = pit_counts[float(tau)] / n_scored
            calibration.append({
                "tau": float(tau),
                "nominal": float(tau),
                "empirical": round(empirical, 4),
                "gap": round(abs(empirical - float(tau)), 4),
            })
    result["calibration"] = calibration

    # --- Recalibration calibration block (additive) ---
    if recalibrate and r_recal_cache:
        pit_counts_recal = {float(tau): 0 for tau in taus}
        n_scored_recal = 0
        # r_recal_cache entries correspond to per_round entries in order.
        for r_recal_t, pr in zip(r_recal_cache, per_round):
            y_t = float(pr["y"])
            r_recal_arr = np.asarray(r_recal_t, dtype=np.float64)
            if r_recal_arr.size == len(taus):
                n_scored_recal += 1
                for k, tau in enumerate(taus):
                    if y_t <= r_recal_arr[k]:
                        pit_counts_recal[float(tau)] += 1
        calibration_recal = []
        if n_scored_recal > 0:
            for tau in taus:
                empirical = pit_counts_recal[float(tau)] / n_scored_recal
                calibration_recal.append({
                    "tau": float(tau),
                    "nominal": float(tau),
                    "empirical": round(empirical, 4),
                    "gap": round(abs(empirical - float(tau)), 4),
                })
        result["calibration_recal"] = calibration_recal

    # --- Sensitivity summary ---
    # Bugfix clause 1.4 / 2.4: optimal_params / optimal_improvement_pct
    # are now read from a sweep artefact produced by
    # scripts/run_sensitivity_sweep.py rather than hardcoded. When no
    # artefact is provided (or the file is missing), the sensitivity
    # block flags the missing sweep and omits the optimal_* keys.
    default_pct = (
        round((mean_mechanism - mean_uniform) / mean_uniform * 100, 1)
        if mean_uniform > 0 else 0.0
    )
    sensitivity_block: dict = {
        "default_params": {"gamma": 4, "rho": 0.1, "lam": 0.05, "eta": 2.0},
        "default_improvement_pct": default_pct,
    }
    if sweep_artefact and os.path.exists(sweep_artefact):
        try:
            with open(sweep_artefact) as _sf:
                sweep_data = json.load(_sf)
            # Sweep file may be keyed by series or flat; try both shapes.
            series_block = sweep_data.get(series_name, sweep_data)
            if (
                isinstance(series_block, dict)
                and "optimal_params" in series_block
                and "optimal_improvement_pct" in series_block
            ):
                sensitivity_block["source"] = sweep_artefact
                sensitivity_block["optimal_params"] = series_block["optimal_params"]
                sensitivity_block["optimal_improvement_pct"] = (
                    series_block["optimal_improvement_pct"]
                )
                sensitivity_block["note"] = (
                    "Recomputed on a held-out split; see "
                    "scripts/run_sensitivity_sweep.py."
                )
            else:
                sensitivity_block["note"] = (
                    f"sensitivity_sweep.json at {sweep_artefact} is missing "
                    f"optimal_params/optimal_improvement_pct for series "
                    f"'{series_name}'."
                )
        except Exception as _exc:
            sensitivity_block["note"] = (
                f"Failed to read sensitivity_sweep.json: {_exc}. "
                f"Run scripts/run_sensitivity_sweep.py to regenerate."
            )
    else:
        sensitivity_block["note"] = (
            "sensitivity_sweep.json not found — run "
            "scripts/run_sensitivity_sweep.py to populate optimal_params "
            "and optimal_improvement_pct."
        )
    result["sensitivity"] = sensitivity_block

    # --- Diebold-Mariano tests ---
    # Uses Andrews (1991) data-driven HAC bandwidth by default (stats.py
    # fix B1). This is more conservative than the legacy horizon-1
    # bandwidth on autocorrelated real-data series; the reported
    # ``statistic`` and ``p_value`` are now defensible against an
    # econometrics-literate reviewer. The legacy horizon-1 values are
    # also emitted for back-compat and as a sensitivity check.
    crps_uniform_arr = np.array(crps_per_rule["uniform"])
    crps_mechanism_arr = np.array(crps_per_rule["mechanism"])
    dm_mech = diebold_mariano_test(crps_uniform_arr, crps_mechanism_arr, h=1)
    dm_mech_legacy = diebold_mariano_test(
        crps_uniform_arr, crps_mechanism_arr, h=1, hac_bandwidth=None
    )
    result["dm_test"] = {
        "statistic": round(dm_mech["dm_stat"], 4),
        "p_value": round(dm_mech["p_value"], 6),
        "significant_at_001": dm_mech["p_value"] < 0.001,
        "significant_at_005": dm_mech["p_value"] < 0.05,
        "comparison": "uniform vs mechanism",
        "hac_lag": int(dm_mech["hac_lag"]),
        "hac_bandwidth_mode": dm_mech["hac_bandwidth_mode"],
        "statistic_legacy_horizon1": round(dm_mech_legacy["dm_stat"], 4),
    }

    crps_skill_arr = np.array(crps_per_rule["skill"])
    dm_skill = diebold_mariano_test(crps_uniform_arr, crps_skill_arr, h=1)
    dm_skill_legacy = diebold_mariano_test(
        crps_uniform_arr, crps_skill_arr, h=1, hac_bandwidth=None
    )
    result["dm_test_skill"] = {
        "statistic": round(dm_skill["dm_stat"], 4),
        "p_value": round(dm_skill["p_value"], 6),
        "significant_at_001": dm_skill["p_value"] < 0.001,
        "significant_at_005": dm_skill["p_value"] < 0.05,
        "comparison": "uniform vs skill",
        "hac_lag": int(dm_skill["hac_lag"]),
        "hac_bandwidth_mode": dm_skill["hac_bandwidth_mode"],
        "statistic_legacy_horizon1": round(dm_skill_legacy["dm_stat"], 4),
    }

    # --- Per-agent CRPS time series (downsampled) ---
    # Emits both indexed keys (crps_0, crps_1, ...) for legacy consumers AND
    # name-keyed entries (forecaster_name -> crps) for callers that look up
    # by forecaster name. The dashboard Model Audit panel relies on the
    # latter; earlier code only emitted the indexed form, breaking lookups.
    per_agent_crps_history = []
    step_agent = max(1, (T - warmup) // 600)
    for t in range(warmup, T, step_agent):
        entry: dict = {"t": t}
        for i in range(n_forecasters):
            c = float(crps_hat_from_quantiles(float(y_all[t]), q_reports[i:i+1, t, :], taus)[0])
            c = round(c, 6)
            entry[f"crps_{i}"] = c
            entry[forecasters[i].name] = c
        per_agent_crps_history.append(entry)
    result["per_agent_crps"] = per_agent_crps_history

    # --- Per-agent skill history (for dashboard skill recognition chart) ---
    # Downsample to ~600 points for reasonable JSON size
    sigma_hist = res["sigma_hist"]  # (n_forecasters, T)
    score_hist = res.get("score_hist")  # (n_forecasters, T) if store_history
    wager_hist = res["wager_hist"]  # (n_forecasters, T)

    step = max(1, (T - warmup) // 600)
    skill_history = []
    for t in range(warmup, T, step):
        entry: dict = {"t": t}
        for i in range(n_forecasters):
            name = forecasters[i].name
            sigma_v = round(float(sigma_hist[i, t]), 6)
            weight_v = round(float(wager_hist[i, t]), 6)
            # Indexed keys (legacy consumers: ResultsPage, ContributionsChartSlide)
            entry[f"sigma_{i}"] = sigma_v
            entry[f"weight_{i}"] = weight_v
            # Name-keyed entries (new consumers: audit SkillAllocationPanel
            # uses convergenceRound() which ranks by row[forecasterName]).
            entry[name] = sigma_v
            if score_hist is not None:
                score_v = round(float(score_hist[i, t]), 6)
                entry[f"score_{i}"] = score_v
        skill_history.append(entry)

    # Steady-state σ (average of last 20% of rounds)
    tail_start = warmup + int(0.8 * (T - warmup))
    steady_state = []
    for i in range(n_forecasters):
        tail_sigma = sigma_hist[i, tail_start:T]
        tail_wager = wager_hist[i, tail_start:T]
        avg_score = float(np.mean(score_hist[i, tail_start:T])) if score_hist is not None else None
        steady_state.append({
            "forecaster": forecasters[i].name,
            "index": i,
            "mean_sigma": round(float(np.mean(tail_sigma)), 6),
            "mean_weight": round(float(np.mean(tail_wager)), 6),
            "mean_score": round(avg_score, 6) if avg_score is not None else None,
        })
    # Sort by mean_sigma descending (best forecaster first)
    steady_state.sort(key=lambda x: x["mean_sigma"], reverse=True)

    result["skill_history"] = skill_history
    result["steady_state"] = steady_state
    result["forecaster_names"] = [fc.name for fc in forecasters]

    # Fallback summary (fallback summary property 1.9 / 2.9). Surfaces each
    # forecaster's end-of-run fallback_counter so downstream consumers
    # can detect silent ML-training failures that otherwise appear as
    # XGBoost/MLP rows.
    fallback_summary = {fc.name: int(fc.fallback_counter) for fc in forecasters}
    result["fallback_summary"] = fallback_summary

    # Post-audit issue #3: surface structural forecaster caveats so the
    # "ARIMA(2,1,1)" / "Neural Net (MLP)" row labels don't mislead.
    # ARIMA's predict() returns self._history[-1] (persistence); its
    # fitted model contributes only to the residual distribution.
    result["forecaster_descriptions"] = {
        fc.name: {
            "is_persistence": bool(getattr(fc, "is_persistence", False)),
            "note": (
                "ARIMA.predict() returns the last observation; the fitted "
                "ARIMA model contributes only to the residual-bootstrap "
                "quantile fan, not to the point forecast."
                if "ARIMA" in fc.name
                else ""
            ),
        }
        for fc in forecasters
    }

    if strict_no_fallback:
        offenders = {k: v for k, v in fallback_summary.items() if v > 0}
        if offenders:
            raise ValueError(
                f"strict_no_fallback=True: non-zero fallback counters: {offenders}"
            )

    # Write output
    out_path = os.path.join(outdir, "real_data", series_name)
    os.makedirs(os.path.join(out_path, "data"), exist_ok=True)
    with open(os.path.join(out_path, "data", "comparison.json"), "w") as f:
        json.dump(result, f, indent=2)

    # Print summary
    print(f"\n  Results (post-warmup, {T - warmup} rounds):")
    print(f"  {'Method':15s} {'Mean CRPS':>12s} {'Delta':>12s}")
    print(f"  {'-'*40}")
    for r in rows:
        d = r['delta_crps_vs_equal']
        print(f"  {r['method']:15s} {r['mean_crps']:12.6f} {d:+12.6f}")

    print("\n  Skill ranking (steady-state σ, last 20% of rounds):")
    print(f"  {'Forecaster':25s} {'σ':>8s} {'Weight':>8s} {'Score':>8s}")
    print(f"  {'-'*52}")
    for ss in steady_state:
        score_str = f"{ss['mean_score']:.4f}" if ss['mean_score'] is not None else "N/A"
        print(f"  {ss['forecaster']:25s} {ss['mean_sigma']:8.4f} {ss['mean_weight']:8.4f} {score_str:>8s}")

    print("\n  Diebold-Mariano tests (H0: equal predictive accuracy):")
    dm_m = result["dm_test"]
    sig_m = "***" if dm_m["significant_at_001"] else ("*" if dm_m["significant_at_005"] else "")
    print(f"  Uniform vs Mechanism: DM={dm_m['statistic']:+.4f}, p={dm_m['p_value']:.6f} {sig_m}")
    dm_s = result["dm_test_skill"]
    sig_s = "***" if dm_s["significant_at_001"] else ("*" if dm_s["significant_at_005"] else "")
    print(f"  Uniform vs Skill:     DM={dm_s['statistic']:+.4f}, p={dm_s['p_value']:.6f} {sig_s}")

    return result
