#!/usr/bin/env Rscript
# NO DOTTED LINES: solid/dashed only; dotted patterns render as pixel noise at print scale.
# Fixed deposit: m/sigma and m/b per agent (generated by R)
args <- commandArgs(trailingOnly = TRUE)
outdir <- if (length(args) >= 1) args[1] else "outputs"

if (!requireNamespace("ggplot2", quietly = TRUE)) {
  stop("Install ggplot2: install.packages('ggplot2')")
}
library(ggplot2)

PINK <- "#E91E8C"
BLUE <- "#0088FF"

plot_file <- file.path(outdir, "fixed_deposit_skill_effect_plot.csv")
params_file <- file.path(outdir, "fixed_deposit_skill_effect_params.csv")

if (!file.exists(plot_file)) stop("Missing: ", plot_file)
d <- read.csv(plot_file)
d$m_over_b <- as.numeric(as.character(d$m_over_b))
params <- if (file.exists(params_file)) read.csv(params_file) else data.frame(min_ratio = NA)
min_ratio <- if (nrow(params) > 0) params$min_ratio[1] else NA

agents <- sort(unique(d$agent))
n_show <- length(agents)
out_file <- file.path(outdir, "fixed_deposit_skill_effect.png")

plot_list <- list()
for (i in agents) {
  di <- d[d$agent == i, ]
  rw <- range(di$wager, na.rm = TRUE)
  rs <- range(di$sigma, na.rm = TRUE)
  if (diff(rs) < 1e-12) rs <- c(rs[1], rs[1] + 1)
  scale_sigma <- diff(rw) / diff(rs)
  shift_sigma <- rw[1] - rs[1] * scale_sigma
  di$sigma_scaled <- di$sigma * scale_sigma + shift_sigma

  p_left <- ggplot(di, aes(x = t)) +
    geom_line(aes(y = wager), color = BLUE, linewidth = 0.8) +
    geom_line(aes(y = sigma_scaled), color = PINK, linewidth = 0.8) +
    scale_y_continuous(
      name = "m",
      sec.axis = sec_axis(~ (. - shift_sigma) / scale_sigma, name = "sigma")
    ) +
    labs(title = sprintf("Agent %d: m and sigma", i)) +
    theme_minimal(base_size = 11) +
    theme(
      plot.title = element_text(margin = margin(b = 6)),
      plot.margin = margin(12, 14, 10, 12),
      axis.title.y.left  = element_text(color = BLUE, margin = margin(r = 8)),
      axis.text.y.left   = element_text(color = BLUE),
      axis.title.y.right = element_text(color = PINK, margin = margin(l = 8)),
      axis.text.y.right  = element_text(color = PINK),
      panel.grid.minor   = element_blank()
    )

  p_right <- ggplot(di, aes(x = t, y = m_over_b)) +
    geom_hline(yintercept = 1, linetype = "solid", color = PINK, alpha = 0.6, linewidth = 0.4) +
    geom_line(color = PINK, linewidth = 0.8) +
    labs(y = "m/b", title = sprintf("Agent %d: m/b", i)) +
    theme_minimal(base_size = 11) +
    theme(
      plot.title = element_text(margin = margin(b = 6)),
      plot.margin = margin(12, 14, 10, 12),
      panel.grid.minor = element_blank()
    )
  if (!is.na(min_ratio)) p_right <- p_right + geom_hline(yintercept = min_ratio, linetype = "solid", color = PINK, alpha = 0.6, linewidth = 0.4)

  plot_list[[length(plot_list) + 1]] <- p_left
  plot_list[[length(plot_list) + 1]] <- p_right
}

png(out_file, width = 1000, height = 300 * n_show, res = 100)
if (requireNamespace("gridExtra", quietly = TRUE)) {
  print(do.call(gridExtra::grid.arrange, c(plot_list, ncol = 2, nrow = n_show)))
} else {
  grid::grid.newpage()
  grid::pushViewport(grid::viewport(layout = grid::grid.layout(n_show, 2)))
  for (i in seq_along(agents)) {
    print(plot_list[[2 * i - 1]], vp = grid::viewport(layout.pos.row = i, layout.pos.col = 1))
    print(plot_list[[2 * i]], vp = grid::viewport(layout.pos.row = i, layout.pos.col = 2))
  }
}
invisible(dev.off())
cat("Saved", out_file, "\n")
