#!/usr/bin/env Rscript
# Settlement sanity: budget gap g_t, min payout, profit/ROI/budget_gap histograms (generated by R)
args <- commandArgs(trailingOnly = TRUE)
outdir <- if (length(args) >= 1) args[1] else "outputs"

if (!requireNamespace("ggplot2", quietly = TRUE)) {
  stop("Install ggplot2: install.packages('ggplot2')")
}
library(ggplot2)

PINK <- "#E91E8C"

hist_file <- file.path(outdir, "settlement_sanity_hist.csv")
series_file <- file.path(outdir, "settlement_sanity_series.csv")
metrics_file <- file.path(outdir, "settlement_sanity.csv")
out_file <- file.path(outdir, "settlement_sanity.png")

if (!file.exists(hist_file) || !file.exists(metrics_file)) {
  stop("Missing CSV files: ", hist_file, " or ", metrics_file)
}

d <- read.csv(hist_file)
metrics <- read.csv(metrics_file, na.strings = c("NA", "nan", "NaN", ""))
rownames(metrics) <- metrics$metric
mean_profit <- as.numeric(metrics["mean_profit", "value"])
std_profit <- as.numeric(metrics["std_profit", "value"])
mean_roi <- as.numeric(metrics["mean_roi", "value"])
max_budget_gap <- as.numeric(metrics["max_abs_budget_gap", "value"])
equal_scores_ok <- as.numeric(metrics["equal_scores_ok", "value"])
if (is.na(equal_scores_ok)) equal_scores_ok <- NA

textstr <- sprintf(
  "mean_profit = %s\nstd_profit  = %s\nmean_roi    = %s\nmax_|g_t| = %s\nequal_scores_ok = %s",
  format(mean_profit, digits = 4),
  format(std_profit, digits = 4),
  format(mean_roi, digits = 4),
  format(max_budget_gap, digits = 4),
  if (!is.na(equal_scores_ok)) as.integer(equal_scores_ok) else "NA"
)

panel_theme <- theme_minimal(base_size = 11) +
  theme(
    plot.title = element_text(margin = margin(b = 6)),
    plot.margin = margin(12, 16, 10, 14),
    panel.grid.minor = element_blank()
  )

# Profit histogram
p1 <- ggplot(d[d$series == "profit", ], aes(x = value)) +
  geom_histogram(bins = 30, fill = "white", color = PINK, linewidth = 0.8, alpha = 0.8) +
  labs(x = "Profit", y = "Count", title = "Settlement sanity: profit histogram") +
  panel_theme

# ROI histogram with metrics
p2 <- ggplot(d[d$series == "roi", ], aes(x = value)) +
  geom_histogram(bins = 30, fill = "white", color = PINK, linewidth = 0.8, alpha = 0.8) +
  annotate("label", x = Inf, y = Inf, label = textstr, hjust = 1.05, vjust = 1.1,
           size = 2.5, family = "monospace", fill = "white", color = PINK,
           label.size = 0.2, label.padding = unit(0.25, "lines")) +
  labs(x = "ROI", y = "Count", title = "Settlement sanity: ROI histogram") +
  panel_theme

# Budget gap g_t over rounds and histogram of g_t
if (file.exists(series_file)) {
  s <- read.csv(series_file)
  p_gt <- ggplot(s, aes(x = round, y = budget_gap)) +
    geom_line(color = PINK, linewidth = 0.6) +
    geom_hline(yintercept = 0, linetype = "solid", color = "gray60", linewidth = 0.4) +
    labs(x = "Round t", y = expression(g[t]), title = "Per-round budget gap") +
    panel_theme
  p_gt_hist <- ggplot(s, aes(x = budget_gap)) +
    geom_histogram(bins = 30, fill = "white", color = PINK, linewidth = 0.8, alpha = 0.8) +
    geom_vline(xintercept = 0, linetype = "solid", color = "gray60", linewidth = 0.4) +
    labs(x = expression(g[t]), y = "Count", title = "Histogram of budget gap") +
    panel_theme
  # Min payout over rounds (should be >= 0)
  if ("min_payout_active" %in% names(s) && any(!is.na(s$min_payout_active))) {
    p_minpay <- ggplot(s[!is.na(s$min_payout_active), ], aes(x = round, y = min_payout_active)) +
      geom_line(color = PINK, linewidth = 0.6) +
      geom_hline(yintercept = 0, linetype = "solid", color = "gray60", linewidth = 0.4) +
      labs(x = "Round t", y = "min payout (active)", title = "Min payout across active agents (>= 0)") +
      panel_theme
  } else {
    p_minpay <- ggplot() + panel_theme + labs(title = "Min payout (no data)")
  }
} else {
  p_gt <- p_gt_hist <- p_minpay <- ggplot() + panel_theme + labs(title = "No series data")
}

# Budget gap histogram from hist_file if present
if (any(d$series == "budget_gap")) {
  p_bg_hist <- ggplot(d[d$series == "budget_gap", ], aes(x = value)) +
    geom_histogram(bins = 30, fill = "white", color = PINK, linewidth = 0.8, alpha = 0.8) +
    geom_vline(xintercept = 0, linetype = "solid", color = "gray60", linewidth = 0.4) +
    labs(x = expression(g[t]), y = "Count", title = "Histogram of budget gap") +
    panel_theme
} else {
  p_bg_hist <- p_gt_hist
}

png(out_file, width = 1280, height = 1080, res = 110)
if (requireNamespace("gridExtra", quietly = TRUE)) {
  if (file.exists(series_file)) {
    print(gridExtra::grid.arrange(p_gt, p_gt_hist, p_minpay, p1, p2, p_bg_hist, ncol = 2))
  } else {
    print(gridExtra::grid.arrange(p1, p2, ncol = 2))
  }
} else {
  grid::grid.newpage()
  grid::pushViewport(grid::viewport(layout = grid::grid.layout(2, 2)))
  print(p1, vp = grid::viewport(layout.pos.row = 1, layout.pos.col = 1))
  print(p2, vp = grid::viewport(layout.pos.row = 1, layout.pos.col = 2))
  print(p_gt, vp = grid::viewport(layout.pos.row = 2, layout.pos.col = 1))
  print(p_gt_hist, vp = grid::viewport(layout.pos.row = 2, layout.pos.col = 2))
}
invisible(dev.off())

cat("Saved", out_file, "\n")
