#!/usr/bin/env Rscript
# NO DOTTED LINES: solid/dashed only; dotted patterns render as pixel noise at print scale.
# Skill/wager under intermittency: one PNG per agent (generated by R)
args <- commandArgs(trailingOnly = TRUE)
outdir <- if (length(args) >= 1) args[1] else "outputs"

if (!requireNamespace("ggplot2", quietly = TRUE)) {
  stop("Install ggplot2: install.packages('ggplot2')")
}
library(ggplot2)

PINK <- "#E91E8C"
BLUE <- "#0088FF"
GRAY <- "#D0D0D0"

plot_file <- file.path(outdir, "skill_wager_intermittency_plot.csv")
params_file <- file.path(outdir, "skill_wager_intermittency_params.csv")

if (!file.exists(plot_file)) stop("Missing: ", plot_file)
d <- read.csv(plot_file)
d$m_over_b <- as.numeric(as.character(d$m_over_b))
params <- if (file.exists(params_file)) read.csv(params_file) else data.frame(min_ratio = NA)
min_ratio <- if (nrow(params) > 0) params$min_ratio[1] else NA

agents <- sort(unique(d$agent))
for (i in agents) {
  di <- d[d$agent == i, ]
  out_file <- file.path(outdir, sprintf("skill_wager_intermittency_agent_%d.png", i))

  # Scale sigma to wager range for dual axis
  rw <- range(di$wager, na.rm = TRUE)
  rs <- range(di$sigma, na.rm = TRUE)
  if (diff(rs) < 1e-12) rs <- c(rs[1], rs[1] + 1)
  scale_sigma <- diff(rw) / diff(rs)
  shift_sigma <- rw[1] - rs[1] * scale_sigma
  di$sigma_scaled <- di$sigma * scale_sigma + shift_sigma

  # Row 1: wager (blue) + sigma (pink, right axis)
  p1 <- ggplot(di, aes(x = t)) +
    geom_rect(data = di[di$missing == 1, ], aes(xmin = t - 0.5, xmax = t + 0.5, ymin = -Inf, ymax = Inf),
              fill = GRAY, alpha = 0.2, inherit.aes = FALSE) +
    geom_line(aes(y = wager), color = BLUE, linewidth = 0.8) +
    geom_line(aes(y = sigma_scaled), color = PINK, linewidth = 0.8) +
    scale_y_continuous(
      name = "m (wager)",
      sec.axis = sec_axis(~ (. - shift_sigma) / scale_sigma, name = "sigma")
    ) +
    scale_color_manual(values = c("m" = BLUE, "sigma" = PINK)) +
    labs(title = sprintf("Agent %d: effective wager and skill", i)) +
    theme_minimal(base_size = 11) +
    theme(
      plot.title = element_text(margin = margin(b = 6)),
      plot.margin = margin(12, 14, 10, 12),
      axis.title.y.left  = element_text(color = BLUE, margin = margin(r = 8)),
      axis.text.y.left   = element_text(color = BLUE),
      axis.title.y.right = element_text(color = PINK, margin = margin(l = 8)),
      axis.text.y.right  = element_text(color = PINK),
      panel.grid.minor   = element_blank()
    )

  # Row 2: m/b
  p2 <- ggplot(di, aes(x = t)) +
    geom_rect(data = di[di$missing == 1, ], aes(xmin = t - 0.5, xmax = t + 0.5, ymin = -Inf, ymax = Inf),
              fill = GRAY, alpha = 0.2, inherit.aes = FALSE) +
    geom_hline(yintercept = 1, linetype = "solid", color = PINK, alpha = 0.6, linewidth = 0.4) +
    geom_line(aes(y = m_over_b), color = PINK, linewidth = 0.8) +
    labs(y = "m/b", title = "Skill lever (m/b)") +
    theme_minimal(base_size = 11) +
    theme(
      plot.title = element_text(margin = margin(b = 6)),
      plot.margin = margin(12, 14, 10, 12),
      panel.grid.minor = element_blank()
    )
  if (!is.na(min_ratio)) p2 <- p2 + geom_hline(yintercept = min_ratio, linetype = "solid", color = PINK, alpha = 0.6, linewidth = 0.4)

  # Row 3: profit and cum_profit
  p3 <- ggplot(di, aes(x = t)) +
    geom_rect(data = di[di$missing == 1, ], aes(xmin = t - 0.5, xmax = t + 0.5, ymin = -Inf, ymax = Inf),
              fill = GRAY, alpha = 0.2, inherit.aes = FALSE) +
    geom_hline(yintercept = 0, linetype = "solid", color = PINK, alpha = 0.5, linewidth = 0.5) +
    geom_line(aes(y = profit), color = PINK, alpha = 0.7, linewidth = 0.8) +
    geom_line(aes(y = cum_profit), color = PINK, linewidth = 1.5) +
    labs(x = "t", y = "profit", title = "Per-round and cumulative profit") +
    theme_minimal(base_size = 11) +
    theme(
      plot.title = element_text(margin = margin(b = 6)),
      plot.margin = margin(12, 14, 10, 12),
      panel.grid.minor = element_blank()
    )

  png(out_file, width = 1000, height = 800, res = 100)
  if (requireNamespace("gridExtra", quietly = TRUE)) {
    print(gridExtra::grid.arrange(p1, p2, p3, nrow = 3))
  } else {
    grid::grid.newpage()
    grid::pushViewport(grid::viewport(layout = grid::grid.layout(3, 1)))
    print(p1, vp = grid::viewport(layout.pos.row = 1, layout.pos.col = 1))
    print(p2, vp = grid::viewport(layout.pos.row = 2, layout.pos.col = 1))
    print(p3, vp = grid::viewport(layout.pos.row = 3, layout.pos.col = 1))
  }
  invisible(dev.off())
  cat("Saved", out_file, "\n")
}
