const BASE = import.meta.env.BASE_URL;

/**
 * Slide 8 right panel: Skill Signal — ggplot2-generated exponential decay curve.
 * Shows σ = σ_min + (1 − σ_min) · exp(−γ · L) with three forecaster dots.
 * Generated by scripts/plot_skill_signal.R
 */
export default function SkillSignalSlide() {
  return (
    <div style={{
      width: '100%',
      height: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 4,
    }}>
      <img
        src={`${BASE}presentation-plots/skill_signal_clean.png`}
        alt="Skill mapping: σ = σ_min + (1−σ_min)·exp(−γ·L) with three forecaster examples"
        style={{ flex: 1, maxWidth: '100%', maxHeight: '100%', objectFit: 'contain', borderRadius: 8 }}
      />
    </div>
  );
}
