#!/usr/bin/env python3
"""Compare pre-fix vs post-fix JSON outputs from the model-training-testing-audit
spec and emit a consolidated delta report.

Pre-fix snapshot: ``onlinev2/outputs/pre_fix_snapshot/<series>/<file>.json``
                  (captured before any fix from this spec landed).
Post-fix current: ``dashboard/public/data/real_data/<series>/data/<file>.json``
                  (regenerated by ``scripts/run_real_data_with_skill.py`` and
                  ``scripts/run_baseline_comparison.py`` and
                  ``scripts/run_sensitivity_sweep.py``).

Emits: ``onlinev2/outputs/post_fix_deltas/consolidated_deltas.json`` with
one row per ``(dataset, block, method)`` showing pre- and post-fix mean
CRPS, absolute delta, and percentage delta.

Usage::

    onlinev2/.venv/bin/python scripts/compare_pre_post_fix_outputs.py
"""
from __future__ import annotations

import json
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PRE_FIX_ROOT = REPO_ROOT / "onlinev2" / "outputs" / "pre_fix_snapshot"
POST_FIX_ROOT = REPO_ROOT / "dashboard" / "public" / "data" / "real_data"
# Some pre-fix snapshots (audit_fresh) have their post-fix counterpart
# under onlinev2/outputs/real_data/ rather than dashboard/public/data/.
POST_FIX_ONLINEV2_ROOT = REPO_ROOT / "onlinev2" / "outputs" / "real_data"
OUT_PATH = REPO_ROOT / "onlinev2" / "outputs" / "post_fix_deltas" / "consolidated_deltas.json"


# Block name renames introduced by this spec (bugfix clauses 1.12-1.14).
# Align legacy names on the left side to their post-fix counterparts on
# the right so the diff lines up.
METHOD_RENAMES = {
    "michael_ogd": "michael_ogd_centered_median_fan",
}
BLOCK_RENAMES = {
    "rep_holdout": "online_window_mean",
    "prequential_blocks": "online_block_mean",
}


def _rows_to_method_map(rows: list) -> dict[str, float]:
    """Extract method → mean_crps from a list of row dicts."""
    out = {}
    for r in rows:
        name = r.get("method")
        if name is None:
            continue
        renamed = METHOD_RENAMES.get(name, name)
        out[renamed] = float(r.get("mean_crps", float("nan")))
    return out


def _load_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def _compare_rows(pre: dict | None, post: dict | None, dataset: str, block: str) -> list[dict]:
    """Compare the `rows` arrays in two JSON payloads."""
    if pre is None or post is None:
        return []
    pre_rows = _rows_to_method_map(pre.get("rows", []))
    post_rows = _rows_to_method_map(post.get("rows", []))
    methods = sorted(set(pre_rows) | set(post_rows))
    out = []
    for m in methods:
        pre_val = pre_rows.get(m)
        post_val = post_rows.get(m)
        delta = None
        delta_pct = None
        if pre_val is not None and post_val is not None:
            delta = post_val - pre_val
            delta_pct = (delta / pre_val * 100) if pre_val != 0 else None
        out.append({
            "dataset": dataset,
            "block": block,
            "method": m,
            "pre_fix_mean_crps": pre_val,
            "post_fix_mean_crps": post_val,
            "delta_crps": delta,
            "delta_pct": round(delta_pct, 2) if delta_pct is not None else None,
            "renamed_from": next(
                (k for k, v in METHOD_RENAMES.items() if v == m), None
            ),
        })
    return out


def main() -> None:
    datasets = [d.name for d in PRE_FIX_ROOT.iterdir() if d.is_dir()]
    print(f"Pre-fix datasets: {datasets}")

    all_rows: list[dict] = []
    missing_post: list[str] = []

    for dataset in datasets:
        pre_dir = PRE_FIX_ROOT / dataset
        post_dir = POST_FIX_ROOT / dataset / "data"
        if not post_dir.exists():
            # Some audit datasets (audit_fresh) live under
            # onlinev2/outputs/real_data/<dataset>/data/ instead of
            # the dashboard tree. Fall back to that path.
            alt_post_dir = POST_FIX_ONLINEV2_ROOT / dataset / "data"
            if alt_post_dir.exists():
                post_dir = alt_post_dir
            else:
                print(f"  [{dataset}] WARNING: post-fix dir missing at {post_dir}")
                missing_post.append(dataset)
                continue
        for pre_file in sorted(pre_dir.glob("*.json")):
            block = pre_file.stem
            post_file = post_dir / pre_file.name
            pre_data = _load_json(pre_file)
            post_data = _load_json(post_file)
            if post_data is None:
                all_rows.append({
                    "dataset": dataset,
                    "block": block,
                    "method": None,
                    "note": f"post-fix file missing: {post_file}",
                })
                continue
            all_rows.extend(_compare_rows(pre_data, post_data, dataset, block))

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "pre_fix_root": str(PRE_FIX_ROOT.relative_to(REPO_ROOT)),
        "post_fix_root": str(POST_FIX_ROOT.relative_to(REPO_ROOT)),
        "missing_post_datasets": missing_post,
        "method_renames": METHOD_RENAMES,
        "block_renames": BLOCK_RENAMES,
        "rows": all_rows,
        "note": (
            "CRPS values shift between pre-fix and post-fix because the "
            "training pipeline switched from whole-series min/max "
            "normalization to strictly-causal causal_normalize "
            "(bugfix clause 1.1 / 2.1). The delta reported here is the "
            "net effect of all 14 bug fixes combined; per-fix isolation "
            "requires separate regenerations per task."
        ),
    }
    with open(OUT_PATH, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"Wrote {OUT_PATH}")
    print(f"Rows compared: {len(all_rows)}")


if __name__ == "__main__":
    main()
